### ISSUE TITLE
Error when creating plugin: The node API for `babel` has been moved to `babel-core`

### ISSUE THREAD

**Issue by jmatsushita** [sighjs/sigh#21]
Hi again.

I've followed the instructions on writing a plugin and I got the following error when running ```sigh -w``` after generating the plugin scaffold the default options :
```
Error: The node API for `babel` has been moved to `babel-core`.
    at Object.<anonymous> (.../node_modules/babel/index.js:1:69)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at process.prepare (eval at <anonymous> (.../node_modules/sigh/node_modules/process-pool/lib/childProcess.js:14:15), <anonymous>:2:15)
    at process.<anonymous> (.../node_modules/sigh/node_modules/process-pool/lib/childProcess.js:16:20)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by jmatsushita** [comment]
Pinning babel to version 5 works so there should probably be an upper bound in sigh-babel for now.

**Comment by ohjames** [comment]
Released a new `sigh-babel` with a more restrictive peer dependency on babel.

**Comment by ohjames** [comment]
sigh-babel 0.12.0 supports babel 6 now.
