### ISSUE TITLE
sigh plugin scaffolding: babel version issue

### ISSUE THREAD

**Issue by Strate** [sighjs/sigh#27]
```
sigh -p plugin-name
# answer a questions
cd sigh-plugin-name
sigh -w

/devel/src/hotfix/megaplan/front/build/sigh/sigh-typescript/node_modules/babel/index.js:1
(function (exports, require, module, __filename, __dirname) { throw new Error("The node API for `babel` has been moved to `babel-core`.");
                                                              ^

Error: The node API for `babel` has been moved to `babel-core`.
    at Object.<anonymous> (/devel/src/hotfix/megaplan/front/build/sigh/sigh-typescript/node_modules/babel/index.js:1:69)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at process.prepare (eval at <anonymous> (/devel/src/hotfix/megaplan/front/build/sigh/sigh-typescript/node_modules/process-pool/lib/childProcess.js:14:15), <anonymous>:2:15)
    at process.<anonymous> (/devel/src/hotfix/megaplan/front/build/sigh/sigh-typescript/node_modules/process-pool/lib/childProcess.js:16:20)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:695:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
/devel/src/hotfix/megaplan/front/build/sigh/sigh-typescript/node_modules/babel/index.js:1
(function (exports, require, module, __filename, __dirname) { throw new Error("The node API for `babel` has been moved to `babel-core`.");
                                                              ^

Error: The node API for `babel` has been moved to `babel-core`.
    at Object.<anonymous> (/devel/src/hotfix/megaplan/front/build/sigh/sigh-typescript/node_modules/babel/index.js:1:69)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at process.prepare (eval at <anonymous> (/devel/src/hotfix/megaplan/front/build/sigh/sigh-typescript/node_modules/process-pool/lib/childProcess.js:14:15), <anonymous>:2:15)
    at process.<anonymous> (/devel/src/hotfix/megaplan/front/build/sigh/sigh-typescript/node_modules/process-pool/lib/childProcess.js:16:20)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:695:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
^C
```

Seems that it is babel version issue.

**Comment by ohjames** [comment]
Please update sigh, the latest version pegs the peer dependency version of babel to 5. There is a ticket in the `sigh-babel` project for updating.

**Comment by ohjames** [comment]
I'll double check the version pegging is affecting the scaffolder.

**Comment by Strate** [comment]
@ohjames I have made a fresh install an hour ago

**Comment by ohjames** [comment]
Weird, checkout https://github.com/sighjs/sigh-babel/blob/master/package.json#L32 the version of babel should be pegged below version 6. Maybe it has used an earlier `sigh-babel` or something.

**Comment by ohjames** [comment]
Okay so `npm install pkg` doesn't respect `peerDependency` versions of other dependencies. At least it gives you a warning. I need to make a change... somewhere...

**Comment by ohjames** [comment]
Since yeoman's `npmInstall` does not respect peer dependencies (just like `npm install`) then... I guess ideally I need a yeoman API that will install all unresolved peer dependencies. Otherwise I'll have to write that myself or hack it, either of which is kinda annoying ;)

**Comment by ohjames** [comment]
With the latest version (released in the last 10 minutes) you just need to `npm install babel@5` inside the project after it has been generated for you. Which of course is less than ideal.

**Comment by ohjames** [comment]
Check out [this yeoman issue](https://github.com/yeoman/generator-angular/issues/1205). Basically... there is no way around this issue. I shoulda chosen a better generator. Argh.

**Comment by Strate** [comment]
Or you can update sigh-babel to babel 6 =)
Okay, I am go to manually change dependency of babel

**Comment by ohjames** [comment]
I've updated the docs for now and sigh-cli, ideally need to find a way to handle it automatically, or just update sigh-babel to babel 6.
