### ISSUE TITLE
sighjs.github.io is broken

### ISSUE THREAD

**Issue by unlight** [sighjs/sigh#50]
Chrome/52.0.2741.0
Presentation is not loading.
```
es6-module-loader.js:1 Potentially unhandled rejection [2] TypeError: Error loading "init" at http://sighjs.github.io/build/init.js
Failed to execute 'animate' on 'Element': duration must be non-negative or auto.
    at TypeError (native)
    at initEffects (http://sighjs.github.io/build/init.js:1:2563)
    at init (http://sighjs.github.io/build/init.js:1:5072)
    at Function.<anonymous> (http://sighjs.github.io/build/init.js:1:5468)
    at execute (http://sighjs.github.io/build/jspm_packages/system.js:1:14731)
    at f (http://sighjs.github.io/build/jspm_packages/system.js:1:5970)
    at l (http://sighjs.github.io/build/jspm_packages/system.js:1:4597)
    at Object.execute (http://sighjs.github.io/build/jspm_packages/system.js:1:8278)
    at o (http://sighjs.github.io/build/jspm_packages/es6-module-loader.js:1:18496)
    at p (http://sighjs.github.io/build/jspm_packages/es6-module-loader.js:1:18868)
```

**Comment by ohjames** [comment]
It works for me

**Comment by robations** [comment]
Hmm, well doesn't work for me, right now. This is really strange, I have the same problem with:

MacOS: Chrome, Firefox, Safari, Opera (all latest versions)
Win7: IE11

I get the same error as above and a blankish screen (spotty pattern and a left sidebar).

What does work is iOS Safari.

Also in MacOS Safari, http://sighjs.github.io/ works, but https://sighjs.github.io does not.

**Comment by robations** [comment]
Safari is erratic, there isn't actually difference between http and https. If I hit refresh in quick succession it's generally not working, so seems like some kind of timing error. Possible this is a bigger issue if you have an empty cache, but I'm now going to read the goddamn page instead of debugging it :)
